name: CloudFlare

on:
  workflow_dispatch:
  schedule:
    - cron: 0 16 * * *

env:
  UPLOAD_DIR: 'uploads'
  PUSH_BRANCH: 'release/cloudflare'
  NODE_VERSION: '18'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup env
        run: |
          mkdir -p ${{ env.UPLOAD_DIR }}
          echo "TAG_NAME=$(date +"%Y.%m.%d")" >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: npm install and download
        working-directory: src
        run: |
          npm install
          mkdir -p ./configs
          echo "UPLOAD_DIR=${{ env.UPLOAD_DIR }}" > .env
          echo "URL_PREFIX=${{ vars.CF_URL_PREFIX }}" >> .env
          echo "${{ vars.CLASH }}" > ./configs/CLASH
          echo "${{ vars.QUANTUMULTX }}" > ./configs/QUANTUMULTX
          node index.js

      - name: Upload files to R2 bucket
        uses: willfurstenau/r2-dir-upload@main
        with:
          accountid: ${{ secrets.CF_ACCOUNT_ID }}
          accesskeyid: ${{ secrets.CF_ACCESS_KEY }}
          secretaccesskey: ${{ secrets.CF_SECRET_KEY }}
          bucket: ${{ secrets.R2_BUCKET }}
          source: ${{ github.workspace }}/${{ env.UPLOAD_DIR }}
          destination: /

      # - name: Push to "${{ env.PUSH_BRANCH }}" branch
      #   run: |
      #     cd ${{ env.UPLOAD_DIR }}
      #     git init
      #     git config user.name "${{ github.actor }}"
      #     git config user.email "${{ github.actor }}@users.noreply.github.com"
      #     git checkout -b ${{ env.PUSH_BRANCH }}
      #     git add .
      #     git commit -m "commit ${{ env.TAG_NAME }}"
      #     git remote add origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
      #     git push -f origin ${{ env.PUSH_BRANCH }}

      - name: Push changes to "${{ env.PUSH_BRANCH }}" branch
        run: |
          git clone -b ${{ env.PUSH_BRANCH }} "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" release_branch
          cd release_branch
          git rm -rf .
          cp -rv ../${{ env.UPLOAD_DIR }}/* .
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add -A .
          git commit -m "commit ${{ env.TAG_NAME }}"
          git push -f origin ${{ env.PUSH_BRANCH }}
