name: TencentCloud

on:
  workflow_dispatch:
  repository_dispatch:
    types: [profile-changed]
  schedule:
    - cron: 0 12 * * *

env:
  UPLOAD_DIR: 'uploads'
  PUSH_BRANCH: 'release/tencentcloud'
  NODE_VERSION: '20'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup env
        run: |
          mkdir -p ${{ env.UPLOAD_DIR }}
          echo "TAG_NAME=$(date +"%Y.%m.%d")" >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: npm install and download
        working-directory: src
        run: |
          npm install
          mkdir -p ./configs
          echo "UPLOAD_DIR=${{ env.UPLOAD_DIR }}" > .env
          echo "URL_PREFIX=${{ vars.TC_URL_PREFIX }}" >> .env
          echo "${{ vars.CLASH }}" > ./configs/CLASH
          echo "${{ vars.QUANTUMULTX }}" > ./configs/QUANTUMULTX
          node index.js

      - name: Upload files to Tencent COS and refresh CDN
        uses: sylingd/tencent-cos-and-cdn-action@v1.0.2
        with:
          secret_id: ${{ secrets.TC_SECRET_ID }}
          secret_key: ${{ secrets.TC_SECRET_KEY }}
          cos_bucket: ${{ vars.TC_COS_BUCKET }}
          cos_region: ${{ vars.TC_COS_REGION }}
          cos_accelerate: false
          cdn_prefix: ${{ vars.TC_URL_PREFIX }}
          local_path: ${{ env.UPLOAD_DIR }}
          remote_path: /
          clean: false

      # - name: Push to "${{ env.PUSH_BRANCH }}" branch
      #   run: |
      #     cd ${{ env.UPLOAD_DIR }}
      #     git init
      #     git config user.name "${{ github.actor }}"
      #     git config user.email "${{ github.actor }}@users.noreply.github.com"
      #     git checkout -b ${{ env.PUSH_BRANCH }}
      #     git add .
      #     git commit -m "commit ${{ env.TAG_NAME }}"
      #     git remote add origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
      #     git push -f origin ${{ env.PUSH_BRANCH }}

      - name: Push changes to "${{ env.PUSH_BRANCH }}" branch
        run: |
          git clone -b ${{ env.PUSH_BRANCH }} "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" release_branch
          cd release_branch
          git rm -rf .
          cp -rv ../${{ env.UPLOAD_DIR }}/* .
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add -A .
          git commit --allow-empty -m "commit ${{ env.TAG_NAME }}"
          git push -f origin ${{ env.PUSH_BRANCH }}
